### ISSUE TITLE
exporting to Simplicity Studio using yotta requires update

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/Third_Party_Int#1]
There are instructions about exporting to Simplicity Studio using yotta.
This has to be updated and show how to do it with mbed CLI:
https://docs.mbed.com/docs/third-party-integrations/en/latest/Simp_Stu/simp_stu/

**Comment by iriark01** [comment]
@MarceloSalazar is this still relevant? Can someone from your team provide updated instructions?

**Comment by MarceloSalazar** [comment]
Yes, this is still relevant, there is mention of yotta on the 'latest' version of the doc.
We should probably just remove the doc and section.
https://docs.mbed.com/docs/third-party-integrations/en/latest/

**Comment by iriark01** [comment]
I can unpublish it if you want

**Comment by MarceloSalazar** [comment]
Yes please, then let's close this ticket :)
